name: Build and Deploy WASM

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏁
        uses: actions/checkout@v4

      - name: Setup Go 🐹
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build 🏗️
        run: |
          mkdir -p deploy_out
          
          GOOS=js GOARCH=wasm go build -o deploy_out/main.wasm main.go
          
          curl -L https://raw.githubusercontent.com/golang/go/master/misc/wasm/wasm_exec.js -o deploy_out/wasm_exec.js
          
          cp dist/index.html deploy_out/
          
          cp -r rom deploy_out/
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages